#!/usr/bin/env python3
"""Claude AI-powered code review for pull requests."""

import argparse
import json
import os
import sys
from typing import Optional

import requests
from anthropic import Anthropic

# Initialize Anthropic client
client = Anthropic()

def get_pr_diff(repo: str, pr_number: int, github_token: str) -> str:
    """Fetch the diff for a pull request."""
    url = f"https://api.github.com/repos/{repo}/pulls/{pr_number}"
    headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3.diff"
    }
    
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    return response.text

def get_pr_details(repo: str, pr_number: int, github_token: str) -> dict:
    """Fetch PR title and description."""
    url = f"https://api.github.com/repos/{repo}/pulls/{pr_number}"
    headers = {"Authorization": f"token {github_token}"}
    
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    return response.json()

def analyze_code_with_claude(diff: str, pr_details: dict) -> str:
    """Use Claude to analyze code changes."""
    
    prompt = f"""Review this pull request and provide constructive feedback.

**PR Title:** {pr_details.get('title', 'N/A')}
**PR Description:** {pr_details.get('body', 'No description provided')}

**Code Changes:**
```diff
{diff[:4000]}  # Limit diff size for API
```

Please provide:
1. **Summary** of the changes
2. **Potential Issues** (bugs, security concerns, performance issues)
3. **Best Practices** (code style, maintainability)
4. **Suggestions for Improvement**
5. **Overall Assessment** (approve/needs changes/request changes)

Be concise and constructive."""

    message = client.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=1024,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    
    return message.content[0].text

def post_review_comment(repo: str, pr_number: int, review_text: str, github_token: str):
    """Post Claude's review as a comment on the PR."""
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {"Authorization": f"token {github_token}"}
    
    # Format as a review comment
    body = f"""## 🤖 Claude AI Code Review

{review_text}

---
*This review was generated by Claude AI. Please review and use your own judgment.*"""
    
    response = requests.post(
        url,
        headers=headers,
        json={"body": body}
    )
    response.raise_for_status()
    print(f"✅ Review posted to PR #{pr_number}")

def main():
    parser = argparse.ArgumentParser(description="Claude AI Code Review")
    parser.add_argument("--pr-number", type=int, required=True)
    parser.add_argument("--repo", required=True)
    
    args = parser.parse_args()
    
    api_key = os.getenv("CLAUDE_API_KEY")
    github_token = os.getenv("GITHUB_TOKEN")
    
    if not api_key:
        print("❌ Error: CLAUDE_API_KEY not set")
        sys.exit(1)
    if not github_token:
        print("❌ Error: GITHUB_TOKEN not set")
        sys.exit(1)
    
    try:
        print(f"📝 Fetching PR #{args.pr_number} from {args.repo}...")
        pr_details = get_pr_details(args.repo, args.pr_number, github_token)
        diff = get_pr_diff(args.repo, args.pr_number, github_token)
        
        print("🤔 Claude is analyzing the code...")
        review = analyze_code_with_claude(diff, pr_details)
        
        print("📤 Posting review to GitHub...")
        post_review_comment(args.repo, args.pr_number, review, github_token)
        
    except Exception as e:
        print(f"❌ Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
