#!/usr/bin/env python3
"""Claude AI-powered issue analysis and categorization."""

import argparse
import os
import sys

import requests
from anthropic import Anthropic

client = Anthropic()

def get_issue_details(repo: str, issue_number: int, github_token: str) -> dict:
    """Fetch issue details from GitHub API."""
    url = f"https://api.github.com/repos/{repo}/issues/{issue_number}"
    headers = {"Authorization": f"token {github_token}"}
    
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    return response.json()

def analyze_issue_with_claude(issue: dict) -> str:
    """Use Claude to analyze and categorize an issue."""
    
    prompt = f"""Analyze this GitHub issue and provide insights.

**Title:** {issue.get('title', 'N/A')}
**Body:** {issue.get('body', 'No description')}
**Labels:** {', '.join([l['name'] for l in issue.get('labels', [])])}

Please provide:
1. **Issue Category** (bug/feature/documentation/question/etc.)
2. **Severity/Priority** (if applicable)
3. **Summary** of the issue
4. **Suggested Solution** or next steps
5. **Relevant Tags/Labels** to apply

Be concise and actionable."""

    message = client.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=800,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    
    return message.content[0].text

def post_issue_comment(repo: str, issue_number: int, analysis: str, github_token: str):
    """Post Claude's analysis as a comment."""
    url = f"https://api.github.com/repos/{repo}/issues/{issue_number}/comments"
    headers = {"Authorization": f"token {github_token}"}
    
    body = f"""## 🤖 Claude AI Analysis

{analysis}

---
*This analysis was generated by Claude AI. Please review the suggestions.*"""
    
    response = requests.post(
        url,
        headers=headers,
        json={"body": body}
    )
    response.raise_for_status()
    print(f"✅ Analysis posted to issue #{issue_number}")

def main():
    parser = argparse.ArgumentParser(description="Claude AI Issue Analysis")
    parser.add_argument("--issue-number", type=int, required=True)
    parser.add_argument("--repo", required=True)
    
    args = parser.parse_args()
    
    api_key = os.getenv("CLAUDE_API_KEY")
    github_token = os.getenv("GITHUB_TOKEN")
    
    if not api_key:
        print("❌ Error: CLAUDE_API_KEY not set")
        sys.exit(1)
    if not github_token:
        print("❌ Error: GITHUB_TOKEN not set")
        sys.exit(1)
    
    try:
        print(f"📝 Fetching issue #{args.issue_number}...")
        issue = get_issue_details(args.repo, args.issue_number, github_token)
        
        print("🤔 Claude is analyzing the issue...")
        analysis = analyze_issue_with_claude(issue)
        
        print("📤 Posting analysis to GitHub...")
        post_issue_comment(args.repo, args.issue_number, analysis, github_token)
        
    except Exception as e:
        print(f"❌ Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
