"""initial schema v3

Revision ID: a54050fcc6cd
Revises: 
Create Date: 2026-08-26 18:02:53.209976
"""
import sqlalchemy as sa

from alembic import op

revision = 'a54050fcc6cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_safety_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('soc_compliance_tier', sa.String(length=64), nullable=False),
    sa.Column('protection_layer', sa.String(length=64), nullable=False),
    sa.Column('alert_severity', sa.Integer(), nullable=False),
    sa.Column('regulatory_schema_status', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('ai_safety_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_safety_events_alert_severity'), ['alert_severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_safety_events_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_safety_events_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('approval_requests',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('phase', sa.String(length=64), nullable=True),
    sa.Column('technique_id', sa.String(length=32), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'EXPIRED', name='approvalstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload_detail', sa.JSON(), nullable=False),
    sa.Column('origin_module', sa.String(length=64), nullable=True),
    sa.Column('pqc_entry_id', sa.Uuid(), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_requested_by'), ['requested_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_status'), ['status'], unique=False)

    op.create_table('encryption_keys',
    sa.Column('key_id', sa.Uuid(), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ROTATED', 'REVOKED', name='keystatus'), nullable=False),
    sa.Column('wrapped_key', sa.LargeBinary(), nullable=False),
    sa.Column('wrap_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('key_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key_id')
    )
    with op.batch_alter_table('encryption_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encryption_keys_status'), ['status'], unique=False)

    op.create_table('fabric_modules',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('pillar', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('maturity', sa.Enum('TRADITIONAL', 'INITIAL', 'ADVANCED', 'OPTIMAL', name='maturitylevel'), nullable=False),
    sa.Column('operational_status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('fabric_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fabric_modules_pillar'), ['pillar'], unique=False)

    op.create_table('operators',
    sa.Column('operator_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'OPERATOR', 'APPROVER', 'ADMIN', name='role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('operator_id')
    )
    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operators_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_operators_role'), ['role'], unique=False)

    op.create_table('payload_executions',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('payload_id', sa.String(length=64), nullable=False),
    sa.Column('technique_id', sa.String(length=32), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=True),
    sa.Column('ontology_refs', sa.JSON(), nullable=False),
    sa.Column('command_set', sa.JSON(), nullable=False),
    sa.Column('approval_request_id', sa.Uuid(), nullable=True),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('operator_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('execution_id')
    )
    with op.batch_alter_table('payload_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payload_executions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payload_executions_payload_id'), ['payload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payload_executions_technique_id'), ['technique_id'], unique=False)

    op.create_table('pqc_audit_log',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('operator_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=128), nullable=False),
    sa.Column('action_detail', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('pqc_signature', sa.Text(), nullable=False),
    sa.Column('classical_signature', sa.Text(), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('classical_public_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('entry_id')
    )
    with op.batch_alter_table('pqc_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pqc_audit_log_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pqc_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pqc_audit_log_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pqc_audit_log_payload_hash'), ['payload_hash'], unique=False)

    op.create_table('quantum_jobs',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('circuit_name', sa.String(length=64), nullable=False),
    sa.Column('backend', sa.String(length=64), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('quantum_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quantum_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quantum_jobs_status'), ['status'], unique=False)

    op.create_table('quantum_orbital_comms',
    sa.Column('comm_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('computational_agent_id', sa.String(length=64), nullable=False),
    sa.Column('inference_chain_hash', sa.String(length=128), nullable=False),
    sa.Column('quantum_entropy_seed', sa.String(length=128), nullable=False),
    sa.Column('execution_latency_ms', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('comm_id')
    )
    with op.batch_alter_table('quantum_orbital_comms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quantum_orbital_comms_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_quantum_orbital_comms_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('zt_posture_assessments',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('overall_level', sa.Enum('TRADITIONAL', 'INITIAL', 'ADVANCED', 'OPTIMAL', name='maturitylevel'), nullable=False),
    sa.Column('per_pillar', sa.JSON(), nullable=False),
    sa.Column('operator_id', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    with op.batch_alter_table('zt_posture_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zt_posture_assessments_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('agentic_remediation_tasks',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('target_machine_ip', sa.String(length=64), nullable=False),
    sa.Column('patch_id', sa.String(length=128), nullable=False),
    sa.Column('autonomous_action_taken', sa.Text(), nullable=False),
    sa.Column('approval_request_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'AWAITING_APPROVAL', 'IN_PROGRESS', 'COMPLETED', 'ROLLED_BACK', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('deployment_progress', sa.Integer(), nullable=False),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.request_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('task_id')
    )
    with op.batch_alter_table('agentic_remediation_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agentic_remediation_tasks_approval_request_id'), ['approval_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agentic_remediation_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agentic_remediation_tasks_target_machine_ip'), ['target_machine_ip'], unique=False)

    op.create_table('key_rotation_history',
    sa.Column('rotation_id', sa.Uuid(), nullable=False),
    sa.Column('old_key_id', sa.Uuid(), nullable=False),
    sa.Column('new_key_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('rotated_by', sa.String(length=64), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['new_key_id'], ['encryption_keys.key_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_key_id'], ['encryption_keys.key_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rotation_id')
    )
    with op.batch_alter_table('key_rotation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_key_rotation_history_old_key_id'), ['old_key_id'], unique=False)

    op.create_table('unified_security_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('source_module', sa.String(length=64), nullable=False),
    sa.Column('threat_category', sa.String(length=64), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('approval_request_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.request_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('unified_security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unified_security_events_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_unified_security_events_source_module'), ['source_module'], unique=False)
        batch_op.create_index(batch_op.f('ix_unified_security_events_threat_category'), ['threat_category'], unique=False)
        batch_op.create_index('ix_use_module_cat', ['source_module', 'threat_category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unified_security_events', schema=None) as batch_op:
        batch_op.drop_index('ix_use_module_cat')
        batch_op.drop_index(batch_op.f('ix_unified_security_events_threat_category'))
        batch_op.drop_index(batch_op.f('ix_unified_security_events_source_module'))
        batch_op.drop_index(batch_op.f('ix_unified_security_events_recorded_at'))

    op.drop_table('unified_security_events')
    with op.batch_alter_table('key_rotation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_key_rotation_history_old_key_id'))

    op.drop_table('key_rotation_history')
    with op.batch_alter_table('agentic_remediation_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agentic_remediation_tasks_target_machine_ip'))
        batch_op.drop_index(batch_op.f('ix_agentic_remediation_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_agentic_remediation_tasks_approval_request_id'))

    op.drop_table('agentic_remediation_tasks')
    with op.batch_alter_table('zt_posture_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zt_posture_assessments_recorded_at'))

    op.drop_table('zt_posture_assessments')
    with op.batch_alter_table('quantum_orbital_comms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quantum_orbital_comms_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_quantum_orbital_comms_event_type'))

    op.drop_table('quantum_orbital_comms')
    with op.batch_alter_table('quantum_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quantum_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_quantum_jobs_created_at'))

    op.drop_table('quantum_jobs')
    with op.batch_alter_table('pqc_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pqc_audit_log_payload_hash'))
        batch_op.drop_index(batch_op.f('ix_pqc_audit_log_operator_id'))
        batch_op.drop_index(batch_op.f('ix_pqc_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_pqc_audit_log_agent_id'))

    op.drop_table('pqc_audit_log')
    with op.batch_alter_table('payload_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payload_executions_technique_id'))
        batch_op.drop_index(batch_op.f('ix_payload_executions_payload_id'))
        batch_op.drop_index(batch_op.f('ix_payload_executions_created_at'))

    op.drop_table('payload_executions')
    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operators_role'))
        batch_op.drop_index(batch_op.f('ix_operators_email'))

    op.drop_table('operators')
    with op.batch_alter_table('fabric_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fabric_modules_pillar'))

    op.drop_table('fabric_modules')
    with op.batch_alter_table('encryption_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encryption_keys_status'))

    op.drop_table('encryption_keys')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_status'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_risk_level'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_requested_by'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_action_type'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('ai_safety_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_safety_events_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_ai_safety_events_client_id'))
        batch_op.drop_index(batch_op.f('ix_ai_safety_events_alert_severity'))

    op.drop_table('ai_safety_events')
    # ### end Alembic commands ###
